<!DOCTYPE html>
<html>
<head>

<meta charset='UTF-8'>
<meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=no'>
<meta name='apple-touch-fullscreen'       content='yes'>
<meta name='apple-mobile-web-app-capable' content='yes'>
<meta name='apple-mobile-web-app-status-bar-style' content='rgba(228,228,228,1.0)'>

<title>File: Doc Exceptions doc &mdash; Ruby-3.4.7</title>

<link rel='stylesheet'  type='text/css' href='../css/y_fonts.css' />
<link rel='stylesheet'  type='text/css' href='../css/highlight.github.css' />
<link rel='stylesheet'  type='text/css' href='../css/y_style.css' />
<link rel='stylesheet'  type='text/css' href='../css/y_list.css' />
<link rel='stylesheet'  type='text/css' href='../css/y_color.css' />

<script type='text/javascript'>
  var pathId = "doc_exceptions doc",
    relpath = '';

  var t2Info = {
    CSEP: '.',
    ISEP: '#',
    NSEP: '::'
  };
</script>

<script type='text/javascript' charset='utf-8' src='../js/highlight.pack.js'></script>
<script type='text/javascript' charset='utf-8' src='../js/y_app.js'></script>

</head>
<body>
<svg id='y_wait' class viewBox='0 0 90 90'></svg>
<div id='settings' class='hidden'></div>
<div id='y_list' class='d h'>
  <header id='list_header'></header>
  <nav id= 'list_nav' class='y_nav l_nav'>
    <ul id='list_items'></ul>
  </nav>
</div>
<div id='y_toc' class='f h'>
  <header id='toc_header'></header>
  <nav id= 'toc_nav' class='y_nav t_nav'>
  <ol id='toc_items'></ol>
  </nav>
</div>
<div id='y_main' tabindex='-1'>
  <header id='y_header'>
    <div id='y_menu'>
      <a id='home_no_xhr' href='/'>Home</a> &raquo; 
      <a href='.'>Ruby-3.4.7</a> &raquo; 
      <a href='_index.html'>Index</a> &raquo; 
      <span class='title'><a id='t2_doc_top' href='#'>File: Doc Exceptions doc&nbsp;&#x25B2;</a></span>
          </div>

    <a id='list_href' href="file_list.html"></a>
    <div id='y_measure_em' class='y_measure'></div>
    <div id='y_measure_vh' class='y_measure'></div>
    <span id='y_measure_50pre' class='y_measure'><code>123456789_123456789_123456789_123456789_123456789_</code></span>
  </header>
<div id='content' class='file'>
<h1>Exceptions</h1>

<p>Ruby code can raise exceptions.</p>

<p>Most often, a raised exception is meant to alert the running program
that an unusual (i.e., <em>exceptional</em>) situation has arisen,
and may need to be handled.</p>

<p>Code throughout the Ruby core, Ruby standard library, and Ruby gems generates exceptions
in certain circumstances:</p>

<pre class="code rb"><code class="rb">File.open(&#39;nope.txt&#39;) # Raises Errno::ENOENT: &quot;No such file or directory&quot;
</code></pre>

<h2>Raised Exceptions</h2>

<p>A raised exception transfers program execution, one way or another.</p>

<h3>Unrescued Exceptions</h3>

<p>If an exception not <em>rescued</em>
(see <a href="#label-Rescued+Exceptions">Rescued Exceptions</a> below),
execution transfers to code in the Ruby interpreter
that prints a message and exits the program (or thread):</p>

<pre class="code console"><code class="console">$ ruby -e &quot;raise&quot;
-e:1:in &#39;&lt;main&gt;&#39;: unhandled exception
</code></pre>

<h3>Rescued Exceptions</h3>

<p>An <i>exception handler</i> may determine what is to happen
when an exception is raised;
the handler may <em>rescue</em> an exception,
and may prevent the program from exiting.</p>

<p>A simple example:</p>

<pre class="code rb"><code class="rb">begin
  raise &#39;Boom!&#39;                # Raises an exception, transfers control.
  puts &#39;Will not get here.&#39;
rescue
  puts &#39;Rescued an exception.&#39; # Control transferred to here; program does not exit.
end
puts &#39;Got here.&#39;
</code></pre>

<p>Output:</p>

<pre class="code ruby"><code class="ruby"><span class='const'>Rescued</span> <span class='id identifier rubyid_an'>an</span> <span class='id identifier rubyid_exception'>exception</span>.
<span class='const'>Got</span> <span class='id identifier rubyid_here'>here</span>.</code></pre>

<p>An exception handler has several elements:</p>

<table><thead>
<tr>
<th>Element</th>
<th>Use</th>
</tr>
</thead><tbody>
<tr>
<td>Begin clause.</td>
<td>Begins the handler and contains the code whose raised exception, if any, may be rescued.</td>
</tr>
<tr>
<td>One or more rescue clauses.</td>
<td>Each contains &quot;rescuing&quot; code, which is to be executed for certain exceptions.</td>
</tr>
<tr>
<td>Else clause (optional).</td>
<td>Contains code to be executed if no exception is raised.</td>
</tr>
<tr>
<td>Ensure clause (optional).</td>
<td>Contains code to be executed whether or not an exception is raised, or is rescued.</td>
</tr>
<tr>
<td><tt>end</tt> statement.</td>
<td>Ends the handler.  `</td>
</tr>
</tbody></table>

<h4>Begin Clause</h4>

<p>The begin clause begins the exception handler:</p>

<ul>
<li>May start with a <code>begin</code> statement;
see also <a href="#label-Begin-Less+Exception+Handlers">Begin-Less Exception Handlers</a>.</li>
<li>Contains code whose raised exception (if any) is covered
by the handler.</li>
<li>Ends with the first following <code>rescue</code> statement.</li>
</ul>

<h4>Rescue Clauses</h4>

<p>A rescue clause:</p>

<ul>
<li>Starts with a <code>rescue</code> statement.</li>
<li>Contains code that is to be executed for certain raised exceptions.</li>
<li>Ends with the first following <code>rescue</code>,
<code>else</code>, <code>ensure</code>, or <code>end</code> statement.</li>
</ul>

<h5>Rescued Exceptions</h5>

<p>A <code>rescue</code> statement may include one or more classes
that are to be rescued;
if none is given, StandardError is assumed.</p>

<p>The rescue clause rescues both the specified class
(or StandardError if none given) or any of its subclasses;
see <a href="file.Exception@Built-In+Exception+Class+Hierarchy.html">Built-In Exception Class Hierarchy</a>.</p>

<pre class="code rb"><code class="rb">begin
  1 / 0 # Raises ZeroDivisionError, a subclass of StandardError.
rescue
  puts &quot;Rescued #{$!.class}&quot;
end
</code></pre>

<p>Output:</p>

<pre class="code ruby"><code class="ruby"><span class='const'>Rescued</span> <span class='const'>ZeroDivisionError</span></code></pre>

<p>If the <code>rescue</code> statement specifies an exception class,
only that class (or one of its subclasses) is rescued;
this example exits with a ZeroDivisionError,
which was not rescued because it is not ArgumentError or one of its subclasses:</p>

<pre class="code rb"><code class="rb">begin
  1 / 0
rescue ArgumentError
  puts &quot;Rescued #{$!.class}&quot;
end
</code></pre>

<p>A <code>rescue</code> statement may specify multiple classes,
which means that its code rescues an exception
of any of the given classes (or their subclasses):</p>

<pre class="code rb"><code class="rb">begin
  1 / 0
rescue FloatDomainError, ZeroDivisionError
  puts &quot;Rescued #{$!.class}&quot;
end
</code></pre>

<h5>Multiple Rescue Clauses</h5>

<p>An exception handler may contain multiple rescue clauses;
in that case, the first clause that rescues the exception does so,
and those before and after are ignored:</p>

<pre class="code rb"><code class="rb">begin
  Dir.open(&#39;nosuch&#39;)
rescue Errno::ENOTDIR
  puts &quot;Rescued #{$!.class}&quot;
rescue Errno::ENOENT
  puts &quot;Rescued #{$!.class}&quot;
end
</code></pre>

<p>Output:</p>

<pre class="code ruby"><code class="ruby"><span class='const'>Rescued</span> <span class='const'>Errno</span><span class='op'>::</span><span class='const'>ENOENT</span></code></pre>

<h5>Capturing the Rescued \Exception</h5>

<p>A <code>rescue</code> statement may specify a variable
whose value becomes the rescued exception
(an instance of Exception or one of its subclasses:</p>

<pre class="code rb"><code class="rb">begin
  1 / 0
rescue =&gt; x
  puts x.class
  puts x.message
end
</code></pre>

<p>Output:</p>

<pre class="code ruby"><code class="ruby"><span class='const'>ZeroDivisionError</span>
<span class='id identifier rubyid_divided'>divided</span> <span class='id identifier rubyid_by'>by</span> <span class='int'>0</span></code></pre>

<h5>Global Variables</h5>

<p>Two read-only global variables always have <code>nil</code> value
except in a rescue clause;
there:</p>

<ul>
<li><code>$!</code>: contains the rescued exception.</li>
<li><code>$@</code>: contains its backtrace.</li>
</ul>

<p>Example:</p>

<pre class="code rb"><code class="rb">begin
  1 / 0
rescue
  p $!
  p $@
end
</code></pre>

<p>Output:</p>

<pre class="code ruby"><code class="ruby"><span class='comment'>#&lt;ZeroDivisionError: divided by 0&gt;
</span>[<span class='tstring'><span class='tstring_beg'>&quot;</span><span class='tstring_content'>t.rb:2:in &#39;Integer#/&#39;</span><span class='tstring_end'>&quot;</span></span><span class='comma'>,</span> <span class='tstring'><span class='tstring_beg'>&quot;</span><span class='tstring_content'>t.rb:2:in &#39;&lt;main&gt;&#39;</span><span class='tstring_end'>&quot;</span></span>]</code></pre>

<h5>Cause</h5>

<p>In a rescue clause, the method Exception#cause returns the previous value of <code>$!</code>,
which may be <code>nil</code>;
elsewhere, the method returns <code>nil</code>.</p>

<p>Example:</p>

<pre class="code rb"><code class="rb">begin
  raise(&#39;Boom 0&#39;)
rescue =&gt; x0
  puts &quot;Exception: #{x0.inspect};  $!: #{$!.inspect};  cause: #{x0.cause.inspect}.&quot;
  begin
    raise(&#39;Boom 1&#39;)
  rescue =&gt; x1
    puts &quot;Exception: #{x1.inspect};  $!: #{$!.inspect};  cause: #{x1.cause.inspect}.&quot;
    begin
      raise(&#39;Boom 2&#39;)
    rescue =&gt; x2
      puts &quot;Exception: #{x2.inspect};  $!: #{$!.inspect};  cause: #{x2.cause.inspect}.&quot;
    end
  end
end
</code></pre>

<p>Output:</p>

<pre class="code ruby"><code class="ruby"><span class='const'>Exception</span><span class='op'>:</span> <span class='comment'>#&lt;RuntimeError: Boom 0&gt;;  $!: #&lt;RuntimeError: Boom 0&gt;;  cause: nil.
</span><span class='const'>Exception</span><span class='op'>:</span> <span class='comment'>#&lt;RuntimeError: Boom 1&gt;;  $!: #&lt;RuntimeError: Boom 1&gt;;  cause: #&lt;RuntimeError: Boom 0&gt;.
</span><span class='const'>Exception</span><span class='op'>:</span> <span class='comment'>#&lt;RuntimeError: Boom 2&gt;;  $!: #&lt;RuntimeError: Boom 2&gt;;  cause: #&lt;RuntimeError: Boom 1&gt;.</span></code></pre>

<h4>Else Clause</h4>

<p>The <code>else</code> clause:</p>

<ul>
<li>Starts with an <code>else</code> statement.</li>
<li>Contains code that is to be executed if no exception is raised in the begin clause.</li>
<li>Ends with the first following <code>ensure</code> or <code>end</code> statement.</li>
</ul>

<pre class="code rb"><code class="rb">begin
  puts &#39;Begin.&#39;
rescue
  puts &#39;Rescued an exception!&#39;
else
  puts &#39;No exception raised.&#39;
end
</code></pre>

<p>Output:</p>

<pre class="code ruby"><code class="ruby"><span class='const'>Begin</span>.
<span class='const'>No</span> <span class='id identifier rubyid_exception'>exception</span> <span class='id identifier rubyid_raised'>raised</span>.</code></pre>

<h4>Ensure Clause</h4>

<p>The ensure clause:</p>

<ul>
<li>Starts with an <code>ensure</code> statement.</li>
<li>Contains code that is to be executed
regardless of whether an exception is raised,
and regardless of whether a raised exception is handled.</li>
<li>Ends with the first following <code>end</code> statement.</li>
</ul>

<pre class="code rb"><code class="rb">def foo(boom: false)
  puts &#39;Begin.&#39;
  raise &#39;Boom!&#39; if boom
rescue
  puts &#39;Rescued an exception!&#39;
else
  puts &#39;No exception raised.&#39;
ensure
  puts &#39;Always do this.&#39;
end

foo(boom: true)
foo(boom: false)
</code></pre>

<p>Output:</p>

<pre class="code ruby"><code class="ruby"><span class='const'>Begin</span>.
<span class='const'>Rescued</span> <span class='id identifier rubyid_an'>an</span> <span class='id identifier rubyid_exception!'>exception!</span>
<span class='const'>Always</span> <span class='kw'>do</span> <span class='id identifier rubyid_this'>this</span>.
<span class='const'>Begin</span>.
<span class='const'>No</span> <span class='id identifier rubyid_exception'>exception</span> <span class='id identifier rubyid_raised'>raised</span>.
<span class='const'>Always</span> <span class='kw'>do</span> <span class='id identifier rubyid_this'>this</span>.</code></pre>

<h4>End Statement</h4>

<p>The <code>end</code> statement ends the handler.</p>

<p>Code following it is reached only if any raised exception is rescued.</p>

<h4>Begin-Less \Exception Handlers</h4>

<p>As seen above, an exception handler may be implemented with <code>begin</code> and <code>end</code>.</p>

<p>An exception handler may also be implemented as:</p>

<ul>
<li><p>A method body:</p>

<pre class="code rb"><code class="rb">def foo(boom: false) # Serves as beginning of exception handler.
  puts &#39;Begin.&#39;
  raise &#39;Boom!&#39; if boom
rescue
  puts &#39;Rescued an exception!&#39;
else
  puts &#39;No exception raised.&#39;
end                  # Serves as end of exception handler.
</code></pre></li>
<li><p>A block:</p>

<pre class="code rb"><code class="rb">Dir.chdir(&#39;.&#39;) do |dir| # Serves as beginning of exception handler.
  raise &#39;Boom!&#39;
rescue
  puts &#39;Rescued an exception!&#39;
end                     # Serves as end of exception handler.
</code></pre></li>
</ul>

<h4>Re-Raising an \Exception</h4>

<p>It can be useful to rescue an exception, but allow its eventual effect;
for example, a program can rescue an exception, log data about it,
and then &quot;reinstate&quot; the exception.</p>

<p>This may be done via the <code>raise</code> method, but in a special way;
a rescuing clause:</p>

<ul>
<li>Captures an exception.</li>
<li>Does whatever is needed concerning the exception (such as logging it).</li>
<li>Calls method <code>raise</code> with no argument,
which raises the rescued exception:</li>
</ul>

<pre class="code rb"><code class="rb">begin
  1 / 0
rescue ZeroDivisionError
  # Do needful things (like logging).
  raise # Raised exception will be ZeroDivisionError, not RuntimeError.
end
</code></pre>

<p>Output:</p>

<pre class="code ruby"><code class="ruby"><span class='id identifier rubyid_ruby'>ruby</span> <span class='id identifier rubyid_t'>t</span>.<span class='id identifier rubyid_rb'>rb</span>
<span class='id identifier rubyid_t'>t</span>.<span class='id identifier rubyid_rb'>rb</span><span class='symbeg'>:</span><span class='int'>2</span><span class='symbeg'>:</span><span class='kw'>in</span> <span class='tstring'><span class='tstring_beg'>&#39;</span><span class='tstring_content'>Integer#/</span><span class='tstring_end'>&#39;</span></span><span class='op'>:</span> <span class='id identifier rubyid_divided'>divided</span> <span class='id identifier rubyid_by'>by</span> <span class='int'>0</span> (<span class='const'>ZeroDivisionError</span>)
    <span class='id identifier rubyid_from'>from</span> <span class='id identifier rubyid_t'>t</span>.<span class='id identifier rubyid_rb'>rb</span><span class='symbeg'>:</span><span class='int'>2</span><span class='symbeg'>:</span><span class='kw'>in</span> <span class='tstring'><span class='tstring_beg'>&#39;</span><span class='tstring_content'>&lt;main&gt;</span><span class='tstring_end'>&#39;</span></span></code></pre>

<h4>Retrying</h4>

<p>It can be useful to retry a begin clause;
for example, if it must access a possibly-volatile resource
(such as a web page),
it can be useful to try the access more than once
(in the hope that it may become available):</p>

<pre class="code rb"><code class="rb">retries = 0
begin
  puts &quot;Try ##{retries}.&quot;
  raise &#39;Boom&#39;
rescue
  puts &quot;Rescued retry ##{retries}.&quot;
  if (retries += 1) &lt; 3
    puts &#39;Retrying&#39;
    retry
  else
    puts &#39;Giving up.&#39;
    raise
  end
end
</code></pre>

<pre class="code ruby"><code class="ruby"><span class='const'>Try</span> <span class='comment'>#0.
</span><span class='const'>Rescued</span> <span class='kw'>retry</span> <span class='comment'>#0.
</span><span class='const'>Retrying</span>
<span class='const'>Try</span> <span class='comment'>#1.
</span><span class='const'>Rescued</span> <span class='kw'>retry</span> <span class='comment'>#1.
</span><span class='const'>Retrying</span>
<span class='const'>Try</span> <span class='comment'>#2.
</span><span class='const'>Rescued</span> <span class='kw'>retry</span> <span class='comment'>#2.
</span><span class='const'>Giving</span> <span class='id identifier rubyid_up'>up</span>.
<span class='comment'># RuntimeError (&#39;Boom&#39;) raised.</span></code></pre>

<p>Note that the retry re-executes the entire begin clause,
not just the part after the point of failure.</p>

<h2>Raising an \Exception</h2>

<p>\Method Kernel#raise raises an exception.</p>

<h2>Custom Exceptions</h2>

<p>To provide additional or alternate information,
you may create custom exception classes.
Each should be a subclass of one of the built-in exception classes
(commonly StandardError or RuntimeError);
see <a href="file.Exception@Built-In+Exception+Class+Hierarchy.html">Built-In Exception Class Hierarchy</a>.</p>

<pre class="code rb"><code class="rb">class MyException &lt; StandardError; end
</code></pre>

<h2>Messages</h2>

<p>Every <code>Exception</code> object has a message,
which is a string that is set at the time the object is created;
see Exception.new.</p>

<p>The message cannot be changed, but you can create a similar object with a different message;
see Exception#exception.</p>

<p>This method returns the message as defined:</p>

<ul>
<li>Exception#message.</li>
</ul>

<p>Two other methods return enhanced versions of the message:</p>

<ul>
<li>Exception#detailed_message: adds exception class name, with optional highlighting.</li>
<li>Exception#full_message: adds exception class name and backtrace, with optional highlighting.</li>
</ul>

<p>Each of the two methods above accepts keyword argument <code>highlight</code>;
if the value of keyword <code>highlight</code> is <code>true</code>,
the returned string includes bolding and underlining ANSI codes (see below)
to enhance the appearance of the message.</p>

<p>Any exception class (Ruby or custom) may choose to override either of these methods,
and may choose to interpret keyword argument <tt>highlight: true</tt>
to mean that the returned message should contain
<a href="https://en.wikipedia.org/wiki/ANSI_escape_code">ANSI codes</a>
that specify color, bolding, and underlining.</p>

<p>Because the enhanced message may be written to a non-terminal device
(e.g., into an HTML page),
it is best to limit the ANSI codes to these widely-supported codes:</p>

<ul>
<li><p>Begin font color:</p>

<table><thead>
<tr>
<th>Color</th>
<th>ANSI Code</th>
</tr>
</thead><tbody>
<tr>
<td>Red</td>
<td><tt>\e[31m</tt></td>
</tr>
<tr>
<td>Green</td>
<td><tt>\e[32m</tt></td>
</tr>
<tr>
<td>Yellow</td>
<td><tt>\e[33m</tt></td>
</tr>
<tr>
<td>Blue</td>
<td><tt>\e[34m</tt></td>
</tr>
<tr>
<td>Magenta</td>
<td><tt>\e[35m</tt></td>
</tr>
<tr>
<td>Cyan</td>
<td><tt>\e[36m</tt></td>
</tr>
</tbody></table></li>
</ul>

<p><br></p>

<ul>
<li><p>Begin font attribute:</p>

<table><thead>
<tr>
<th>Attribute</th>
<th>ANSI Code</th>
</tr>
</thead><tbody>
<tr>
<td>Bold</td>
<td><tt>\e[1m</tt></td>
</tr>
<tr>
<td>Underline</td>
<td><tt>\e[4m</tt></td>
</tr>
</tbody></table></li>
</ul>

<p><br></p>

<ul>
<li><p>End all of the above:</p>

<table><thead>
<tr>
<th>Color</th>
<th>ANSI Code</th>
</tr>
</thead><tbody>
<tr>
<td>Reset</td>
<td><tt>\e[0m</tt></td>
</tr>
</tbody></table></li>
</ul>

<p>It&#39;s also best to craft a message that is conveniently human-readable,
even if the ANSI codes are included &quot;as-is&quot;
(rather than interpreted as font directives).</p>

<h2>Backtraces</h2>

<p>A <em>backtrace</em> is a record of the methods currently
in the <a href="https://en.wikipedia.org/wiki/Call_stack">call stack</a>;
each such method has been called, but has not yet returned.</p>

<p>These methods return backtrace information:</p>

<ul>
<li>Exception#backtrace: returns the backtrace as an array of strings or <code>nil</code>.</li>
<li>Exception#backtrace_locations: returns the backtrace as an array
of Thread::Backtrace::Location objects or <code>nil</code>.
Each Thread::Backtrace::Location object gives detailed information about a called method.</li>
</ul>

<p>By default, Ruby sets the backtrace of the exception to the location where it
was raised.</p>

<p>The developer might adjust this by either providing <code>backtrace</code> argument
to Kernel#raise, or using Exception#set_backtrace.</p>

<p>Note that:</p>

<ul>
<li>by default, both <code>backtrace</code> and <code>backtrace_locations</code> represent the same backtrace;</li>
<li>if the developer sets the backtrace by one of the above methods to an array of
Thread::Backtrace::Location, they still represent the same backtrace;</li>
<li>if the developer sets the backtrace to a string or an array of strings:

<ul>
<li>by Kernel#raise: <code>backtrace_locations</code> become +nil+;</li>
<li>by Exception#set_backtrace: <code>backtrace_locations</code> preserve the original
value;</li>
</ul></li>
<li>if the developer sets the backtrace to <code>nil</code> by Exception#set_backtrace,
<code>backtrace_locations</code> preserve the original value; but if the exception is then
reraised, both <code>backtrace</code> and <code>backtrace_locations</code> become the location of reraise.</li>
</ul>

<div id='footer'></div>
</div> <!-- content  -->
</div> <!-- y_main   -->
</body>
</html>